services:

  subs-nginx:

    image: nginx:1.29.4-trixie

    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx.subs.conf:/etc/nginx/conf.d/nginx.subs.conf:ro

    depends_on:
      subs-api:
        condition: service_started

    restart: always

    labels:
      filebeat_enable: "true"
      service: "subs-nginx"

    ports:
      - 8009:8000