"""require plan id

Revision ID: f145b12a9d84
Revises: 641b2ac0897f
Create Date: 2026-01-30 00:50:54.553801

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f145b12a9d84'
down_revision: Union[str, Sequence[str], None] = '641b2ac0897f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscription', sa.Column('plan_id', sa.Uuid(), nullable=False))
    op.create_index(op.f('ix_subscription_plan_id'), 'subscription', ['plan_id'], unique=False)
    op.create_foreign_key(None, 'subscription', 'plan', ['plan_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'subscription', type_='foreignkey')  # type: ignore
    op.drop_index(op.f('ix_subscription_plan_id'), table_name='subscription')
    op.drop_column('subscription', 'plan_id')
    # ### end Alembic commands ###
