"""add plan

Revision ID: cad8f3c77236
Revises: 1c7a4c7d0758
Create Date: 2026-01-30 00:38:41.579105

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cad8f3c77236'
down_revision: Union[str, Sequence[str], None] = '1c7a4c7d0758'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscription', sa.Column('starts_at', sa.DateTime(), nullable=False))
    op.add_column('subscription', sa.Column('ends_at', sa.DateTime(), nullable=False))
    op.add_column('subscription', sa.Column('payment_id', sa.Uuid(), nullable=False))
    op.drop_index(op.f('ix_subscription_id'), table_name='subscription')
    op.drop_column('subscription', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscription', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_subscription_id'), 'subscription', ['id'], unique=False)
    op.drop_column('subscription', 'payment_id')
    op.drop_column('subscription', 'ends_at')
    op.drop_column('subscription', 'starts_at')
    # ### end Alembic commands ###
