"""plan name

Revision ID: 641b2ac0897f
Revises: a12aa31faa2d
Create Date: 2026-01-30 00:49:37.058989

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '641b2ac0897f'
down_revision: Union[str, Sequence[str], None] = 'a12aa31faa2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plan', sa.Column('name', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plan', 'name')
    # ### end Alembic commands ###
