services:

  subs-postgres:

    image: postgres:18.1-trixie

    ports: [ 5437:5432 ]

    environment:
      POSTGRES_USER: ${SUBS_POSTGRES_USER:?}
      POSTGRES_PASSWORD: ${SUBS_POSTGRES_PASSWORD:?}
      POSTGRES_DB: ${SUBS_POSTGRES_DB:?}

    healthcheck:
      test: pg_isready -U $${POSTGRES_USER}
      start_interval: 1s
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 5
